### ISSUE TITLE
La lista no tiene porque estar ordenada.

### ISSUE THREAD

**Issue by evolentini** [gustavobastian/TestingIoTTP1#3]
Lo único que debe estar ordenado es la lista de claves que se recupera con la función de devuelve la lista de claves

https://github.com/gustavobastian/TestingIoTTP1/blob/06be0a619b186e58f25212afae6259f902d95239/src/lista.js#L23-L50

**Comment by gustavobastian** [comment]
¿Puede estarlo? No lo encuento en los requisitos. Es por performance?
